export const functionDetail = [
  {
    name: "Graha Shanti",
    img: "../../ganpati.webp",
    imgAlt: "Ganpati image",
    date: "23th November 2023",
    time: "11:00 am",
    address: "7, Suramya Bunglows",
    map: "https://maps.app.goo.gl/2qWE8DdfBW1DoTUR8",
  },
  {
    name: "Mameru",
    img: "../../gold.jpeg",
    imgAlt: "Mameru image",
    date: "23th November 2023",
    time: "11:00 am",
    address: "7, Suramya Bunglows",
    map: "https://maps.app.goo.gl/2qWE8DdfBW1DoTUR8",
  },
  {
    name: "Sangeet",
    img: "../../sangeet.jpeg",
    imgAlt: "sangeet image",
    date: "23/11/2023",
    time: "001",
    address: "aaaa",
    map: "https://maps.app.goo.gl/2qWE8DdfBW1DoTUR8",
  },
  {
    name: "Haldi",
    img: "../../haldi-1.jpeg",
    imgAlt: "Haldi image",
    date: "24/11/2023",
    time: "001",
    address: "aaaa",
    map: "https://maps.app.goo.gl/2qWE8DdfBW1DoTUR8",
  },
  {
    name: "Weeding",
    img: "../../weeding.jpeg",
    imgAlt: "Weeding image",
    date: "25/11/2023",
    time: "001",
    address: "aaaa",
    map: "https://maps.app.goo.gl/2qWE8DdfBW1DoTUR8",
  },
  {
    name: "Reception",
    img: "../../reception.jpeg",
    imgAlt: "Reception image",
    date: "26/11/2023",
    time: "001",
    address: "aaaa",
    map: "https://maps.app.goo.gl/2qWE8DdfBW1DoTUR8",
  },
];
